// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tywynh.Infrastructure.Persistence;

#nullable disable

namespace Tywynh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822174755_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tywynh.Domain.Entities.Confession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alias");

                    b.Property<bool>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("approved");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<bool>("Burned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("burned");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EchoCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("echo_count");

                    b.Property<short>("Intensity")
                        .HasColumnType("smallint")
                        .HasColumnName("intensity");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("moderated_at");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("moderation_status");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("ResonanceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("resonance_count");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_confessions_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_confessions_created_at");

                    b.HasIndex("ModerationStatus")
                        .HasDatabaseName("ix_confessions_moderation_status");

                    b.HasIndex("ResonanceCount")
                        .HasDatabaseName("ix_confessions_resonance_count");

                    b.ToTable("confessions", (string)null);
                });

            modelBuilder.Entity("Tywynh.Domain.Entities.DailyEcho", b =>
                {
                    b.Property<DateTime>("EchoDate")
                        .HasColumnType("date")
                        .HasColumnName("echo_date");

                    b.Property<Guid>("ConfessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("confession_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EchoCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("echo_count");

                    b.HasKey("EchoDate");

                    b.HasIndex("ConfessionId");

                    b.HasIndex("EchoDate")
                        .IsUnique();

                    b.ToTable("daily_echoes", (string)null);
                });

            modelBuilder.Entity("Tywynh.Domain.Entities.DailyEchoInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EchoDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("echo_date");

                    b.Property<bool>("Echoed")
                        .HasColumnType("boolean")
                        .HasColumnName("echoed");

                    b.Property<bool>("RitualCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("ritual_completed");

                    b.Property<string>("VisitorTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("visitor_token_hash");

                    b.HasKey("Id");

                    b.HasIndex("EchoDate", "VisitorTokenHash")
                        .IsUnique();

                    b.ToTable("daily_echo_interactions", (string)null);
                });

            modelBuilder.Entity("Tywynh.Domain.Entities.Resonance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConfessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("confession_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VisitorTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("visitor_token_hash");

                    b.HasKey("Id");

                    b.HasIndex("ConfessionId", "VisitorTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_resonances_confession_visitor");

                    b.ToTable("resonances", (string)null);
                });

            modelBuilder.Entity("Tywynh.Domain.Entities.DailyEcho", b =>
                {
                    b.HasOne("Tywynh.Domain.Entities.Confession", "Confession")
                        .WithMany()
                        .HasForeignKey("ConfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confession");
                });

            modelBuilder.Entity("Tywynh.Domain.Entities.Resonance", b =>
                {
                    b.HasOne("Tywynh.Domain.Entities.Confession", "Confession")
                        .WithMany()
                        .HasForeignKey("ConfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Confession");
                });
#pragma warning restore 612, 618
        }
    }
}
